### PR TITLE
Handle secret storage in Gatekeeper and Weaver properly

### PR DESCRIPTION
**Pull request by PeterCxy**
Gatekeeper and Weaver HALs are used to store secrets (mainly lockscreen and user secrets) in "slots" (for Gatekeeper, it uses `uid` as the keys, but Weaver has a very limited number of slots). In Paralloid, multiple system images will conflict when they try to access the same Gatekeeper / Weaver hardware secret storage, due to the fact that they are not aware of each other.

In Google's DSU implementation, Gatekeeperd offsets user IDs by 1000000 for the DSU system image, while SyntheticPasswordManager tries to avoid using conflicting Weaver slots by recording slot allocation in /metadata. This won't work properly for us though, since we intend to support more than just one extra system image.

This PR tries to address the issues by hooking symbols in libhidlbase to inject our logic before the HAL implementations are called. Specifically,

1. For Gatekeeper, we randomly generate an ID whenever a system image is booted for the first time. In our injected code, we load this ID and use it multiplied to 1000000 as an offset to the user ID
2. In addition, we need to block Gatekeeperd from attempting to clear the state of the security hardware on first boot by creating the coldboot marker before the actual main() executes.
3. For Weaver, we simply hook system_server (app_process) to block libhidlbase from returning any instance of the IWeaver interface. This should cause the framework to fall back to storing secrets purely in Gatekeeper, which we have already handled.

To implement these hooks, I attempted to use `LD_PRELOAD`, but this didn't work for `app_process` since it always has the AT_SECURE flag set thanks to SELinux. To fix `LD_PRELOAD` support, we will need to do way more sepolicy editing than I am happy with. As a result, I resorted to introducing `patchelf` and using it to inject our hook libraries as the first dependency of the binaries.

In addition, the default linker configuration doesn't allow system executables to link to our hook libraries, which means that the linkerconfig needs to be edited. This is done with a wrapper over `app_process` as it has root privileges when it is first started.

Note that `/linkerconfig` didn't exist in all earlier versions of Android (not sure if it existed on Q, but it probably did not exist on P). We will need to fix this by falling back to other paths, but that is for now beyond the scope of this PR.

Test: Lockscreen passwords should work (both being able to be set and be used) on all boot targets; changing password or clearing data on one target (including the internal) and booting it shall not invalidate lockscreen passwords in any other target.

### CODE REVIEW

**Comment by phhusson** [comment]
FWIW rather than patchelf/LD_PRELOAD, I think you can do stuff by dlopen-ing original gatekeeperd? I think this would remove the need for selinux and ldconfig changes.

I don't understand why you say removing Weaver HAL from manifest is tough, or change the name from weaver to waever?

That's a beautiful experimentation, the code is super clean. But this is horrific, let's not do that. Having dual-boot using DSU/GSI hack is IMO enough. Maybe fallback to sw keymaster/rom-specific metadata for other ROMs. I'd rather not have more hacks than magisk, and that beats it singlehanded

**Comment by PeterCxy** [comment]
@phhusson 

> I'd rather not have more hacks than magisk, and that beats it singlehanded

fwiw Magisk has LD_PRELOAD hacks for MagiskHide and its hooks are way more expansive than what I have done here (in fact the self-unmounting trick in my app_process wrapper was learned from Magisk). Of course, if you don't count MagiskHide, then it doesn't have LD_PRELOAD hacks.

I agree maybe we should not have more hacks than Magisk, and that's why I tried to not make my hooks more complicated than what Magisk has.

> Having dual-boot using DSU/GSI hack is IMO enough.

Setting the property on non-internal ROMs can make it stop using the same uids for Gatekeeper, sure, but clearing data on the internal partition will break all other non-internal ROMs immediately without the hack (we can probably fix this with a wrapper over gatekeeperd, though). The Weaver HAL workaround of DSU needs a bit more than just that property iirc.

> I don't understand why you say removing Weaver HAL from manifest is tough, or change the name from weaver to waever?

I thought we need a full-blown XML parser to remove that, but yeah I guess replacing the name would work. Another reason I didn't do that is that I don't actually have a phone with Weaver to test with -- and the hook can be debugged on phones without Weaver, but the XML removal can't.

> I think you can do stuff by dlopen-ing original gatekeeperd

Do you have any more information on how to do hooking via dlopen? I haven't done it before and have no idea how it can be used to hook symbols.

> Maybe fallback to sw keymaster/rom-specific metadata for other ROMs

In my opinion that's even more "horrific" than a LD_PRELOAD / patchelf hook. You will need to not only replace keymaster, but in fact everything related to hw security -- everything that has dependency on the `AuthToken` structure. Not all of these have software implementations (e.g. fingerprint HAL). In addition, we will have to pull in sw HALs from AOSP tree, and I'm not sure how we would be building them outside the AOSP tree (or we can depend on AOSP fully and make them build inside the AOSP tree).

And in this case we'll really need a full-blown XML parser to edit the vintf definitions, since we will have to make sure the vintf version is consistent with whatever sw implementation we pulled in, not just the interface name in the case of the Weaver hack.

In addition to all of that, device vendors often implement multiple functionalities in one HIDL daemon, and in the case of keymaster and keymaster-related services, that's more than often the case. So we cannot just remove the original keymaster, gatekeeper, weaver for good, since there can be dependency on their non-primary HIDL services. That's far from "generic", from my point of view. At the very least, with my hooks, the only thing we are really depending upon more than our other hacks is the ABI of the `libhidlbase` library, which I don't really see changing soon since it is part of vndk.

metadata is unrelated for this issue, though. We don't need ROM-specific metadata to fix any of the issues anyway. (In fact, having ROM-specific metadata breaks more stuff for now because now Weaver can't have any way of knowing which slots have been used)

**Comment by PeterCxy** [comment]
@phhusson 

Correction, Magisk doesn't use LD_PRELOAD or patchelf or injection. It uses LD_PRELOAD to be mapped into the target process's address space, and then invokes `xhook` to hook directly into the PLT table (https://github.com/topjohnwu/Magisk/blob/master/native/jni/inject/entry.cpp, https://github.com/topjohnwu/Magisk/blob/master/native/jni/inject/hook.cpp). I considered `xhook` once but judging from the current state of the project (basically unmaintained) and its higher level of hackiness, I ended up with `patchelf` for this PR.

I still think that this is the only clean and sane way to make multiple ROM images not conflict with each other (at least not break each other completely and make data unrecoverable when the user attempts to set a lockscreen password). It does not depend on the implementation of the OEM's HALs, or the HAL daemons being single-purpose, or the DSU/GSI support work correctly in their system images. It only depends on the ABI of `libhidlbase`.

We could even remove the need for linker config hacking if we go with your approach of replacing `Weaver` with something invalid like `Waever`. `gatekeeperd` doesn't run in an isolated linker namespace, and can link to hook libraries without any change in linker config. (if this changes in the future, the worst case is we need to add linker config editing anyway)

**Comment by PeterCxy** [comment]
Closing this. Will be removing the Weaver hack and hook Gatekeeperd only. We will handle Weaver later with sed or whatever that's sane.

**Pull request closed without merging**
